import string
import random

def generate_random_password(length=12):
    """
    Generates a random password ensuring it contains a mix of lowercase letters,
    uppercase letters, digits, and punctuation.
    The password length must be at least 4 to guarantee all character types.
    If length is less than 4, it will attempt to include as many types as possible.
    """
    if length < 4:
        # For very short passwords, it's hard to guarantee all types.
        # One option is to raise ValueError, another is to do best effort.
        # Current "best effort": use the old simpler method or just a subset.
        # For this implementation, let's ensure it doesn't crash and tries to be diverse.
        # This edge case might need specific requirements if length < 4 is common.
        # Assuming length >= 4 for guaranteed diversity as per typical password policies.
        # If length is very small, the "guarantee" part might be relaxed or characters chosen carefully.
        # For now, if length < 4, we'll just use the original simpler method for those few chars.
        # Or, more simply, one could argue a password of length < 4 shouldn't be generated by this function
        # if strict complexity is always required. Let's enforce minimum length for guarantee.
        if length == 0:
            return ""
        if length == 1: # Only one type possible
            return random.choice(string.ascii_letters + string.digits + string.punctuation)
        # For 2, 3, we can't guarantee all 4 types.
        # This simplified fallback will just pick from the combined pool.
        # A more robust solution for length < 4 would pick from distinct pools up to length.
        characters = string.ascii_letters + string.digits + string.punctuation
        return ''.join(random.choice(characters) for _ in range(length))


    # Define character sets
    lower = string.ascii_lowercase
    upper = string.ascii_uppercase
    digits = string.digits
    punct = string.punctuation

    # Start password with one of each required type
    password_chars = [
        random.choice(lower),
        random.choice(upper),
        random.choice(digits),
        random.choice(punct),
    ]

    # If length is greater than 4, fill the rest with random choices from all sets
    all_chars = lower + upper + digits + punct
    remaining_length = length - 4
    password_chars.extend(random.choice(all_chars) for _ in range(remaining_length))

    # Shuffle the list to ensure the order is random
    random.shuffle(password_chars)

    return "".join(password_chars)

from .models import User

def generate_random_username(email_prefix, length=8, max_attempts=10):
    """
    Generates a random username using an email prefix and checks for uniqueness.

    Args:
        email_prefix (str): The part of the email before the '@' symbol.
        length (int): The desired length of the random part of the username.
        max_attempts (int): Maximum attempts to find a unique username.

    Returns:
        str: A unique username, or None if a unique username cannot be generated.
    """
    # Ensure the base prefix is not too long
    # Django's User model username max_length is 150 by default.
    # We take a portion of the email_prefix and append random chars.
    # Max length for prefix part should be username_max_length - length_of_random_part - 1 (for potential underscore)
    # However, let's keep it simpler: ensure email_prefix isn't excessively long.
    # A more robust solution might truncate email_prefix if it's too long.
    # For now, we'll assume email_prefix is of reasonable length.

    if length > 150: # Django's default User.username max_length
        length = 150


    for attempt in range(max_attempts):
        # Take a part of the email prefix. Let's say up to 10 chars, or less if length is small
        prefix_len_to_use = min(len(email_prefix), 150 - length -1) # -1 for a potential separator if we added one
        if prefix_len_to_use < 0: # This case happens if length is already 150
            prefix_len_to_use = 0


        username_candidate = email_prefix[:prefix_len_to_use]

        # If the prefix part itself is already long, adjust random part length
        current_length_of_random_part = length
        if len(username_candidate) + current_length_of_random_part > 150:
            current_length_of_random_part = 150 - len(username_candidate)

        if current_length_of_random_part < 0: # Should not happen if previous logic is correct
             current_length_of_random_part = 0


        random_suffix = ''.join(random.choices(string.ascii_lowercase + string.digits, k=current_length_of_random_part))
        username_candidate += random_suffix

        # Ensure the final username doesn't exceed 150 chars (should be handled by above logic, but as a safeguard)
        username_candidate = username_candidate[:150]


        if not User.objects.filter(username=username_candidate).exists():
            return username_candidate

    # Fallback or error logging
    # For now, returning None and letting the caller handle it.
    # Consider logging a warning here in a real application.
    # logger.warning(f"Could not generate unique username for {email_prefix} after {max_attempts} attempts.")
    return None
